### ISSUE TITLE
Cześć

### ISSUE THREAD

**Issue by skandaI** [B0R5UK/SimpleChan#1]
Niedawno ktoś wszedł na IRC-a i zostawił mi wiadomość, że napisał silnik imageboardu w node.js - to byłeś Ty?

**Comment by dawid2193487** [comment]
nie to ja byłęm

a tak na serio to mam cos interesującego chociaz dopiero zaczalem robic

**Comment by skandaI** [comment]
Coś interesującego w sensie?

**Comment by dawid2193487** [comment]
technologia z przyszłości

czan niezniszczalny

**Comment by B0R5UK** [comment]
Nope, to nie ja na pewno, nie korzystam z IRCa
